#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

unsetopt correct_all
autoload -Uz history-beginning-search-menu
zle -N history-beginning-search-menu
bindkey '^X^X' history-beginning-search-menu
bindkey '^R' history-incremental-search-backward
bindkey '^E' history-incremental-search-forward
bindkey -v

# Python virtualenv
#source /usr/local/bin/virtualenvwrapper.sh
#workon twc

alias sga='cat ~/.zprezto/modules/git/alias.zsh'
alias watch='watch -c'

# RBENV
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Editor
export EDITOR=vim

# Packer
if [[ -e "/opt/packer/packer" ]]; then
  export PATH=/opt/packer/packer:$PATH
fi

# Terraform
if [[ -e "/opt/terraform/terraform" ]]; then
  export PATH=/opt/terraform/terraform:$PATH
fi

# CHEF
if type "chef" > /dev/null; then
  eval "$(chef shell-init zsh)"
fi

# SSH Keychain
if type "keychain" > /dev/null; then
  keychain --agents ssh id_ed25519_home id_rsa_home id_ed25519_work id_rsa_work
  source ~/.keychain/$(hostname)-sh > /dev/null
fi

# Go Path
export GOPATH=${HOME}/Workspace/gocode

# Travis
[ -f ${HOME}/.travis/travis.sh ] && source ${HOME}/.travis/travis.sh

# DirEnv
if type "direnv" > /dev/null; then
  eval "$(direnv hook zsh)"
fi

# asdf
if type "asdf" > /dev/null; then
  export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
  mkdir -p "${ASDF_DATA_DIR:-$HOME/.asdf}/completions"
  asdf completion zsh >! "${ASDF_DATA_DIR:-$HOME/.asdf}/completions/_asdf"
  # append completions to fpath
  fpath=(${ASDF_DATA_DIR:-$HOME/.asdf}/completions $fpath)
  # initialise completions with ZSH's compinit
  autoload -Uz compinit && compinit
fi

# LOCAL BIN
export PATH=$HOME/.local/bin:$PATH

# AWS
AWS_BASE=~/.aws
AWS_FILES=${AWS_BASE}/aws_files

# OKTA Script
OKTA_EXEC=/usr/local/bin/okta_aws_login.py

# AWS Credentials
aws_on_old() {
  export AWS_FULL=${1}
  export AWS_ACCOUNT=$(echo ${1} | awk -F "_" '{print $1}')
  export AWS_REGION=$(echo ${1} | awk -F "_" '{print $2}')
  export AWS_DEFAULT_REGION="$AWS_REGION"

  # AWS API
  export AWS_CREDENTIAL_FILE=${AWS_FILES}/credential-file_${AWS_ACCOUNT}

  # EC2 API/BOTO
  export AWS_ACCESS_KEY=`cat ${AWS_CREDENTIAL_FILE} |grep aws_access_key_id |cut -d '=' -f 2`
  export AWS_SECRET_KEY=`cat ${AWS_CREDENTIAL_FILE} |grep aws_secret_access_key |cut -d '=' -f 2`
  export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
  export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}

  # CHEF SETTINGS
  export CHEF_CREDENTIAL_FILE=~/.chef/config/chef-settings_${AWS_ACCOUNT}
  export CHEF_SERVER_URL=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_server_url |cut -d '=' -f 2`
  export CHEF_USERNAME=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_username |cut -d '=' -f 2`
  export CHEF_VALIDATOR_NAME=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_validator_name |cut -d '=' -f 2`
  export CHEF_CLIENT_KEY=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_client_key |cut -d '=' -f 2`
  export CHEF_VALIDATOR_KEY=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_validator_key |cut -d '=' -f 2`
  export CHEF_REPO_DIR=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_repo_dir |cut -d '=' -f 2`
  export CLIENT_KEY=${CHEF_CLIENT_KEY}

  # WHISK
  export WHISK_CONFIG=${CHEF_REPO_DIR}/config/whisk-${AWS_FULL}.yml

  # TERRAFORM
  export TF_VAR_project_aws_access_key=${AWS_ACCESS_KEY}
  export TF_VAR_project_aws_secret_key=${AWS_SECRET_KEY}
}

# AWS Credentials via OKTA
aws_on_okta() {
  if  ! which ${OKTA_EXEC} >  /dev/null 2>&1
  then
     echo "okta_aws_login.py does not exist or OKTA_EXEC not set"
     return 1
  fi

  export AWS_FULL=${1}
  export AWS_ACCOUNT=$(echo ${1} | awk -F "_" '{print $1}')
  export AWS_REGION=$(echo ${1} | awk -F "_" '{print $2}')

  # AWS API
  export AWS_CREDENTIAL_FILE=${AWS_FILES}/credential-file-okta_${AWS_ACCOUNT}

  # OKTA
  source ${AWS_FILES}/okta_env_${AWS_ACCOUNT}
  if [ ! -z "$2" ]; then  export OKTA_AWS_ROLE=$2; fi

  # Run okta_aws_login.py to generate AWS credentials and save it to credential file
  python3 ${OKTA_EXEC} -v -s -p ${AWS_ACCOUNT} -R ${AWS_REGION} -e ${AWS_CREDENTIAL_FILE}
  # Sourcing credential file's variables
  source ${AWS_CREDENTIAL_FILE}

  # EC2 API/BOTO
  export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
  export AWS_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
  export AWS_DEFAULT_PROFILE=${AWS_ACCOUNT}
  export AWS_PROFILE=${AWS_DEFAULT_PROFILE}

  # CHEF SETTINGS
  export CHEF_CREDENTIAL_FILE=~/.chef/config/chef-settings_${AWS_ACCOUNT}
  export CHEF_SERVER_URL=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_server_url |cut -d '=' -f 2`
  export CHEF_USERNAME=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_username |cut -d '=' -f 2`
  export CHEF_VALIDATOR_NAME=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_validator_name |cut -d '=' -f 2`
  export CHEF_CLIENT_KEY=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_client_key |cut -d '=' -f 2`
  export CHEF_VALIDATOR_KEY=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_validator_key |cut -d '=' -f 2`
  export CHEF_REPO_DIR=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_repo_dir |cut -d '=' -f 2`
  export CLIENT_KEY=${CHEF_CLIENT_KEY}

  # WHISK
  export WHISK_CONFIG=${CHEF_REPO_DIR}/config/whisk-${AWS_FULL}.yml
}

# AWS Credentials via AWS SSO
aws_on() {
  aws_off
  sleep 0.2

  export AWS_FULL=${1}
  export AWS_ACCOUNT=$(echo ${1} | awk -F "_" '{print $1}')
  export AWS_REGION=$(echo ${1} | awk -F "_" '{print $2}')

  # AWS API
  export AWS_CREDENTIAL_FILE=${AWS_FILES}/credential-file-sso_${AWS_ACCOUNT}

  # SSO
  # Admin, PU, RO
  AWS_ACCESS_LEVEL="Admin"
  if [ ! -z "$2" ]; then AWS_ACCESS_LEVEL=$2; fi

  export AWS_PROFILE=${AWS_ACCOUNT}_${AWS_ACCESS_LEVEL}

  # Login if needed
  aws sts get-caller-identity &> /dev/null
  if [ "$?" != 0 ]; then
    aws sso login
  fi

  aws configure export-credentials --format env >! $AWS_CREDENTIAL_FILE
  # Sourcing credential file's variables
  source ${AWS_CREDENTIAL_FILE}

  # EC2 API/BOTO Legacy
  export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  export AWS_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
  export AWS_SECURITY_TOKEN=${AWS_SESSION_TOKEN}
  export AWS_DEFAULT_PROFILE=${AWS_PROFILE}
#  export AWS_PROFILE=${AWS_DEFAULT_PROFILE}

  # CHEF SETTINGS
  export CHEF_CREDENTIAL_FILE=~/.chef/config/chef-settings_${AWS_ACCOUNT}
  export CHEF_SERVER_URL=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_server_url |cut -d '=' -f 2`
  export CHEF_USERNAME=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_username |cut -d '=' -f 2`
  export CHEF_VALIDATOR_NAME=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_validator_name |cut -d '=' -f 2`
  export CHEF_CLIENT_KEY=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_client_key |cut -d '=' -f 2`
  export CHEF_VALIDATOR_KEY=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_validator_key |cut -d '=' -f 2`
  export CHEF_REPO_DIR=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_repo_dir |cut -d '=' -f 2`
  export CLIENT_KEY=${CHEF_CLIENT_KEY}

  # WHISK
  export WHISK_CONFIG=${CHEF_REPO_DIR}/config/whisk-${AWS_FULL}.yml
}

aws_off() {
  unset AWS_FULL
  unset AWS_ACCOUNT
  unset AWS_REGION
  unset AWS_DEFAULT_REGION
  unset AWS_CREDENTIAL_FILE
  unset AWS_ACCESS_KEY
  unset AWS_SECRET_KEY
  unset AWS_ACCESS_KEY_ID
  unset AWS_SECRET_ACCESS_KEY
  unset AWS_SECURITY_TOKEN
  unset AWS_SESSION_TOKEN
  unset CHEF_CREDENTIAL_FILE
  unset CHEF_SERVER_URL
  unset CHEF_USERNAME
  unset CHEF_VALIDATOR_NAME
  unset CHEF_CLIENT_KEY
  unset CHEF_VALIDATOR_KEY
  unset CHEF_REPO_DIR
  unset CLIENT_KEY
  unset WHISK_CONFIG
  unset TF_VAR_project_aws_access_key
  unset TF_VAR_project_aws_secret_key
  unset TF_VAR_project_aws_token
  unset OKTA_IDP_ENTRY_URL
  unset OKTA_USERNAME
  unset OKTA_AWS_ROLE
  unset OKTA_AWS_DURATION
}

# IBM Credentials
ibm_on() {
  export IBM_FULL=${1}
  export IBM_ACCOUNT=$(echo ${1} | awk -F "_" '{print $1}')
  export IBM_REGION=$(echo ${1} | awk -F "_" '{print $2}')
  export IBM_CREDENTIAL_FILE=~/.ibm/credential-file_ibm-${IBM_ACCOUNT}
  export IAAS_CLASSIC_USERNAME=`cat ${IBM_CREDENTIAL_FILE} | grep softlayer_username |cut -d '=' -f 2`
  export IAAS_CLASSIC_API_KEY=`cat ${IBM_CREDENTIAL_FILE} | grep softlayer_api_key |cut -d '=' -f 2`
  export IBMCLOUD_API_KEY=`cat ${IBM_CREDENTIAL_FILE} | grep cloud_api_key |cut -d '=' -f 2`
  export ETCDV3_USERNAME=`cat ${IBM_CREDENTIAL_FILE} | grep etcdv3_username | cut -d "=" -f 2`
  export ETCDV3_PASSWORD=`cat ${IBM_CREDENTIAL_FILE} | grep etcdv3_password | cut -d "=" -f 2`
  /usr/local/bin/ibmcloud login --apikey $IBMCLOUD_API_KEY -r $IBM_REGION
##  /usr/local/bin/ibmcloud target -g Default -o twc-sun-$IBM_ACCOUNT
}

ibm_off() {
  unset IBM_FULL
  unset IBM_ACCOUNT
  unset IBM_REGION
  unset IBM_CREDENTIAL_FILE
  unset IBM_SL_USERNAME
  unset IBM_SL_API
  unset IBM_CLOUD_API
  unset ETCDV3_USERNAME
  unset ETCDV3_PASSWORD
}

aws_sso_expires_in() {
  if [[ -z $AWS_CREDENTIAL_EXPIRATION ]]; then
    return 0
  fi

  # Convert ISO 8601 date to format macOS date can understand
  # Strip the timezone part for simplicity
  expiration_date=$(echo "${AWS_CREDENTIAL_EXPIRATION}" | sed 's/\([0-9-]*\)T\([0-9:]*\).*/\1 \2/')
  expiration_seconds=$(date -u -j -f "%Y-%m-%d %H:%M:%S" "${expiration_date}" +%s)
  current_seconds=$(date +%s)

  # Calculate difference in seconds
  seconds_remaining=$((expiration_seconds - current_seconds))

  # Convert to a more readable format
  days=$((seconds_remaining / 86400))
  seconds_remaining=$((seconds_remaining % 86400))
  hours=$((seconds_remaining / 3600))
  seconds_remaining=$((seconds_remaining % 3600))
  minutes=$((seconds_remaining / 60))
  seconds=$((seconds_remaining % 60))

  expires_text=""
  if [[ $days -gt 0 ]]; then
    expires_text="${days}d"
  fi
  if [[ $hours -gt 0 ]]; then
    expires_text="${expires_text}${hours}h"
  fi
  if [[ $minutes -gt 0 ]]; then
    expires_text="${expires_text}${minutes}m"
  fi
  expires_text="${expires_text}${seconds}s"

  export AWS_SSO_EXPIRES_IN="$expires_text"
}
