#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

unsetopt correct_all
autoload -Uz history-beginning-search-menu
zle -N history-beginning-search-menu
bindkey '^X^X' history-beginning-search-menu
bindkey '^R' history-incremental-search-backward
bindkey '^E' history-incremental-search-forward
bindkey -v

# Python virtualenv
source /usr/local/bin/virtualenvwrapper.sh
workon twc

alias sga='cat ~/.zprezto/modules/git/alias.zsh'
alias watch='watch -c'

# RBENV
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Editor
export EDITOR=vim

# Packer
if [[ -e "/opt/packer" ]]; then
  export PATH=/opt/packer:$PATH
fi

# Terraform
if [[ -e "/opt/terraform" ]]; then
  export PATH=/opt/terraform:$PATH
fi

# CHEF
if type "chef" > /dev/null; then
  eval "$(chef shell-init zsh)"
fi

# SSH Keychain
if type "keychain" > /dev/null; then
  keychain --agents ssh id_rsa_home id_rsa_twc
  source ~/.keychain/$(hostname)-sh > /dev/null
fi

# Go Path
export GOPATH=${HOME}/Workspace/gocode

# AWS
AWS_BASE=~/.aws
AWS_FILES=${AWS_BASE}/aws_files

# AWS Credentials
aws_on() {
 export AWS_FULL=${1}
 export AWS_ACCOUNT=$(echo ${1} | awk -F "_" '{print $1}')
 export AWS_REGION=$(echo ${1} | awk -F "_" '{print $2}')
 export AWS_DEFAULT_REGION="$AWS_REGION"

 # AWS API
 export AWS_CREDENTIAL_FILE=${AWS_FILES}/credential-file_${AWS_ACCOUNT}

 # EC2 API
 export AWS_ACCESS_KEY=`cat ${AWS_CREDENTIAL_FILE} |grep aws_access_key_id |cut -d '=' -f 2`
 export AWS_SECRET_KEY=`cat ${AWS_CREDENTIAL_FILE} |grep aws_secret_access_key |cut -d '=' -f 2`

 # BOTO
 export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
 export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}

 # CHEF SETTINGS
 export CHEF_CREDENTIAL_FILE=~/.chef/config/chef-settings_${AWS_ACCOUNT}
 export CHEF_SERVER_URL=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_server_url |cut -d '=' -f 2`
 export CHEF_USERNAME=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_username |cut -d '=' -f 2`
 export CHEF_VALIDATOR_NAME=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_validator_name |cut -d '=' -f 2`
 export CHEF_CLIENT_KEY=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_client_key |cut -d '=' -f 2`
 export CHEF_VALIDATOR_KEY=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_validator_key |cut -d '=' -f 2`
 export CHEF_REPO_DIR=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_repo_dir |cut -d '=' -f 2`
 export CLIENT_KEY=${CHEF_CLIENT_KEY}

 # WHISK
 export WHISK_CONFIG=${CHEF_REPO_DIR}/config/whisk-${AWS_FULL}.yml

 # S3CMD
 alias s3cmd="s3cmd -c ${AWS_FILES}/s3cfg_${AWS_ACCOUNT}"

 # TERRAFORM
 export TF_VAR_project_aws_access_key=${AWS_ACCESS_KEY}
 export TF_VAR_project_aws_secret_key=${AWS_SECRET_KEY}
}

aws_off() {
 unset AWS_FULL
 unset AWS_ACCOUNT
 unset AWS_REGION
 unset AWS_DEFAULT_REGION
 unset AWS_CREDENTIAL_FILE
 unset AWS_ACCESS_KEY
 unset AWS_SECRET_KEY
 unset AWS_ACCESS_KEY_ID
 unset AWS_SECRET_ACCESS_KEY
 unalias s3cmd
}
