#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

unsetopt correct_all
autoload -Uz history-beginning-search-menu
zle -N history-beginning-search-menu
bindkey '^X^X' history-beginning-search-menu
bindkey '^R' history-incremental-search-backward
bindkey '^E' history-incremental-search-forward
bindkey -v

# Python virtualenv
source /usr/local/bin/virtualenvwrapper.sh
workon twc

alias sga='cat ~/.zprezto/modules/git/alias.zsh'
alias watch='watch -c'

# RBENV
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Editor
export EDITOR=vim

# Packer
if [[ -e "/usr/local/packer" ]]; then
  export PATH=/usr/local/packer:$PATH
fi

# CHEF
eval "$(chef shell-init zsh)"

# Go Path
export GOPATH=${HOME}/Workspace/gocode

# AWS
AWS_BASE=~/.aws
AWS_FILES=${AWS_BASE}/aws_files
export AWS_DEFAULT_REGION="us-east-1"

# AWS Credentials
aws_on() {
 export AWS_FULL=${1}
 export AWS_ACCOUNT=$(echo ${1} | awk -F "_" '{print $1}')
 # AWS API
 export AWS_CREDENTIAL_FILE=${AWS_FILES}/credential-file_${AWS_ACCOUNT}
 # EC2 API
 export AWS_ACCESS_KEY=`cat ${AWS_CREDENTIAL_FILE} |grep AWSAccessKey |cut -d '=' -f 2`
 export AWS_SECRET_KEY=`cat ${AWS_CREDENTIAL_FILE} |grep AWSSecretKey |cut -d '=' -f 2`
 export AWS_REGION=$(echo ${1} | awk -F "_" '{print $2}')
 # BOTO
 export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
 export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
 # WHISK
 export WHISK_CONFIG=${CHEF_REPO_DIR}/config/whisk-${AWS_FULL}.yml
 # CHEF SETTINGS
 export CHEF_CREDENTIAL_FILE=~/.chef/config/chef-settings_${AWS_ACCOUNT}
 export CHEF_SERVER_URL=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_server_url |cut -d '=' -f 2`
 export CHEF_USERNAME=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_username |cut -d '=' -f 2`
 export CHEF_VALIDATOR_NAME=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_validator_name |cut -d '=' -f 2`
 export CHEF_CLIENT_KEY=${CHEF_USERNAME}-${AWS_ACCOUNT}
 export CHEF_VALIDATOR_KEY=${CHEF_VALIDATOR_NAME}-${AWS_ACCOUNT}
 export CHEF_REPO_DIR=`cat ${CHEF_CREDENTIAL_FILE} | grep chef_repo_dir |cut -d '=' -f 2`
 # S3CMD
 alias s3cmd="s3cmd -c ${AWS_FILES}/s3cfg_${AWS_ACCOUNT}"
}

aws_off() {
 unset AWS_FULL
 unset AWS_ACCOUNT
 unset AWS_CREDENTIAL_FILE
 unset AWS_ACCESS_KEY
 unset AWS_SECRET_KEY
 unset AWS_REGION
 unset AWS_ACCESS_KEY_ID
 unset AWS_SECRET_ACCESS_KEY
 unalias s3cmd
}
